CREATE TABLE CONTATOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	ANIVERSARIO DATE NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	TELEFONE BIGINT NOT NULL,
	CELULAR BIGINT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL
);